## M280 Homework4
* Author: Shuang Gao
* Date: 2018/06/01

### Question 1
For a multivariate count vector $\mathbf{x}=(x_1,\ldots,x_d)$ with batch size $|\mathbf{x}|=\sum_{j=1}^d x_j$, show that the probability mass function for Dirichlet-multinomial distribution is
$$
    f(\mathbf{x} \mid \alpha) 
	= \int_{\Delta_d} \binom{|\mathbf{x}|}{\mathbf{x}} \prod_{j=1}^d p_j^{x_j} \pi(\mathbf{p}) \, d \mathbf{p}  
    = \binom{|\mathbf{x}|}{\mathbf{x}} \frac{\prod_{j=1}^d \Gamma(\alpha_j+x_j)}{\prod_{j=1}^d \Gamma(\alpha_j)} \frac{\Gamma(|\alpha|)}{\Gamma(|\alpha|+|\mathbf{x}|)}
$$
where $\Delta_d$ is the unit simplex in $d$ dimensions and $|\alpha| = \sum_{j=1}^d \alpha_j$.

**Solution:**
$$
\begin{align}
f(\mathbf{x} \mid \alpha) 
&= \int_{\Delta_d} \binom{|\mathbf{x}|}{\mathbf{x}} \prod_{j=1}^d p_j^{x_j} \pi(\mathbf{p}) \, d \mathbf{p} \\
&= \int_{\Delta_d} \binom{|\mathbf{x}|}{\mathbf{x}} \prod_{j=1}^d p_j^{x_j}\frac{\Gamma(|\alpha|)}{\prod_{j=1}^d \Gamma(\alpha_j)} \prod_{j=1}^d p_j^{\alpha_j-1}\,d \mathbf{p}\\
&= \binom{|\mathbf{x}|}{\mathbf{x}} 
\frac{\Gamma(|\alpha|)}{\prod_{j=1}^d \Gamma(\alpha_j)} \int_{\Delta_d} \prod_{j=1}^d p_j^{x_j+\alpha_j-1}\, d\mathbf{p}
\end{align}
$$

Because $\mathbf{p} = (p_1,\ldots, p_d)$ follow a Dirichlet distribution with parameter vector $\alpha = (\alpha_1,\ldots, \alpha_d)$, $\alpha_j>0$, and density
$$
\begin{eqnarray*}
	\pi(\mathbf{p}) =  \frac{\Gamma(|\alpha|)}{\prod_{j=1}^d \Gamma(\alpha_j)} \prod_{j=1}^d p_j^{\alpha_j-1},
\end{eqnarray*} 
$$
where $|\alpha|=\sum_{j=1}^d \alpha_j$.
We can get,
$$
\begin{align}
\int \pi(\mathbf{p})\,d\mathbf{p} 
&= \int \frac{\Gamma(|\alpha|)}{\prod_{j=1}^d \Gamma(\alpha_j)} \prod_{j=1}^d p_j^{\alpha_j-1} \,d\mathbf{p}=1\\
& \therefore \int \prod_{j=1}^d p_j^{\alpha_j-1}\,d\mathbf{p}=\frac{\prod_{j=1}^d\Gamma{(\alpha_j})}{\Gamma{(|\alpha|)}}\hspace{12mm}(1)
\end{align}
$$
In order to get the derivation of $f(\mathbf{x} \mid \alpha) $, Plug $\alpha_j=\alpha_j+x_j$ into equation (1).
Then we have,
$$
\begin{align}
\int \prod_{j=1}^d p_j^{\alpha_j+x_j-1}\,d\mathbf{p}=\frac{\prod_{j=1}^d\Gamma{(\alpha_j}+x_j)}{\Gamma{(|\alpha|+|\mathbf{x}|)}}
\end{align}
$$
Then
$$
\begin{align}
f(\mathbf{x} \mid \alpha) 
&= \binom{|\mathbf{x}|}{\mathbf{x}} 
\frac{\Gamma(|\alpha|)}{\prod_{j=1}^d \Gamma(\alpha_j)} \frac{\prod_{j=1}^d\Gamma{(\alpha_j}+x_j)}{\Gamma{(|\alpha|+|\mathbf{x}|)}}\\
&=  \binom{|\mathbf{x}|}{\mathbf{x}} \frac{\prod_{j=1}^d \Gamma(\alpha_j+x_j)}{\prod_{j=1}^d \Gamma(\alpha_j)} \frac{\Gamma(|\alpha|)}{\Gamma(|\alpha|+|\mathbf{x}|)}
\end{align}
$$


### Question 2

Given independent data points $\mathbf{x}_1, \ldots, \mathbf{x}_n$, show that the log-likelihood is
$$
L(\alpha) = \sum_{i=1}^n \ln \binom{|\mathbf{x}_i|}{\mathbf{x}_i} + \sum_{i=1}^n \sum_{j=1}^d [\ln \Gamma(\alpha_j + x_{ij}) - \ln \Gamma(\alpha_j)] - \sum_{i=1}^n [\ln \Gamma(|\alpha|+|\mathbf{x}_i|) - \ln \Gamma(|\alpha|)]
$$
Is the log-likelihood a concave function?

**Solution:**
$$
\begin{align}
& \because \mathbf{x_1},...,\mathbf{x_n} \text{ are independent}\\ 
& \therefore f(\mathbf{x_1},...,\mathbf{x_n} \mid \alpha) 
= f(\mathbf{x_1}\mid \alpha)...f(\mathbf{x_n\mid \alpha})
\end{align}
$$
$$
\begin{align}
\therefore f(\mathbf{x_1},...,\mathbf{x_n} \mid \alpha) 
= \prod_{i=1}^n \binom{|\mathbf{x_i}|}{\mathbf{x_i}} \frac{\prod_{j=1}^d \Gamma(\alpha_j+x_{ij})}{\prod_{j=1}^d \Gamma(\alpha_j)} \frac{\Gamma(|\alpha|)}{\Gamma(|\alpha|+|\mathbf{x_i}|)}
\end{align}
$$
$$
\begin{align}
\therefore L(\alpha) 
&= \ln (\prod_{i=1}^n \binom{|\mathbf{x_i}|}{\mathbf{x_i}} \frac{\prod_{j=1}^d \Gamma(\alpha_j+x_{ij})}{\prod_{j=1}^d \Gamma(\alpha_j)} \frac{\Gamma(|\alpha|)}{\Gamma(|\alpha|+|\mathbf{x_i}|)})\\
&= \sum_{i=1}^n \ln \binom{|\mathbf{x}_i|}{\mathbf{x}_i} + \sum_{i=1}^n \sum_{j=1}^d [\ln \Gamma(\alpha_j + x_{ij}) - \ln \Gamma(\alpha_j)] - \sum_{i=1}^n [\ln \Gamma(|\alpha|+|\mathbf{x}_i|) - \ln \Gamma(|\alpha|)]
\end{align}
$$

* The function is not concave.

### Question 3

Write Julia function to compute the log-density of the Dirichlet-multinomial distribution.

The log density of the Dirichlet-multinomial distribution for one data point $\mathbf{x}$ is shown as follow:
$$
\begin{align}
L(\alpha) 
&= \ln \binom{|\mathbf{x}|}{\mathbf{x}} +  \sum_{j=1}^d [\ln \Gamma(\alpha_j + x_{j}) - \ln \Gamma(\alpha_j)] - [\ln \Gamma(|\alpha|+|\mathbf{x}|) - \ln \Gamma(|\alpha|)]\\
&=  \ln |\mathbf{x}|! - \ln(x_1!)-...-\ln(x_{64}!)+ \sum_{j=1}^{64} [\ln \Gamma(\alpha_j + x_{j}) - \ln \Gamma(\alpha_j)] - [\ln \Gamma(|\alpha|+|\mathbf{x}|) - \ln \Gamma(|\alpha|)]\\
&=  \ln |\mathbf{x}|! - [\ln \Gamma(|\alpha|+|\mathbf{x}|) - \ln \Gamma(|\alpha|)]+ \sum_{j=1}^{64} [\ln \Gamma(\alpha_j + x_{j}) - \ln \Gamma(\alpha_j)-\ln(x_j!)]
\end{align}
$$



In [194]:
"""
    dirmult_logpdf(x::Vector, α::Vector)
    
Compute the log-pdf of Dirichlet-multinomial distribution with parameter `α` 
at data point `x`.
"""
function dirmult_logpdf(x::Vector, α::Vector)
    # store the sum of x and α
    sumx = sum(x)
    sumα = sum(α)
    
    # store length of x
    lengthx = size(x, 1) 
    
    # part without summation
    logden = lfact(sumx) - lgamma(sumα + sumx) + lgamma(sumα)
    
    # part within summation
    for j in lengthx
       logden += lgamma(α[j] + x[j]) - lgamma(α[j]) - lfact(x[j])  
    end
    
    # return log density
    return logden
end

function dirmult_logpdf!(r::Vector, X::Matrix, α::Vector)
    for j in 1:size(X, 2)
        r[j] = dirmult_logpdf(X[:, j], α)
    end
    return r
end

"""
    dirmult_logpdf(X, α)
    
Compute the log-pdf of Dirichlet-multinomial distribution with parameter `α` 
at each data point in `X`. Each column of `X` is one data point.
"""
function dirmult_logpdf(X::Matrix, α::Vector)
    r = zeros(size(X, 2))
    dirmult_logpdf!(r, X, α)
end


dirmult_logpdf

### Question 4

Read in `optdigits.tra`, the training set of 3823 handwritten digits. Each row contains the 64 counts of a digit and the last element (65th element) indicates what digit it is. For grading purpose, evaluate the total log-likelihood of this data at parameter values $\alpha=(1,\ldots,1)$ using your function in Q3.

In [195]:
# read in train data
path1_tra = "http://hua-zhou.github.io/teaching/biostatm280"
path2_tra = "-2018spring/hw/hw4/optdigits.tra"

train = readdlm(download(path1_tra * path2_tra), ',')

# separte last column which store the digit 
train_x = round.(Int64, train[:, 1:64])
train_digit = round.(Int64, train[:, 65]);


In [196]:
# store size of train data
length_x = size(train_x, 2)
length_obs = size(train_x, 1)

# input α vector
α = round.(Int64, ones(length_x))

sum(dirmult_logpdf(train_x', α))

-638817.993292528

* The total log-likelihood of this data at parameter values $\alpha=(1,\ldots,1)$ is around -638818.

### Question5 
Derive the score function $\nabla L(\alpha)$, observed information matrix $-d^2L(\alpha)$, and Fisher information matrix $\mathbf{E}[-d^2L(\alpha)]$ for the Dirichlet-multinomial distribution.

Comment on why Fisher scoring method is inefficient for computing MLE in this example.

**Solution:**
* **score function**

From part 2, we have 
$$
L(\alpha) = \sum_{i=1}^n \ln \binom{|\mathbf{x}_i|}{\mathbf{x}_i} + \sum_{i=1}^n \sum_{j=1}^d [\ln \Gamma(\alpha_j + x_{ij}) - \ln \Gamma(\alpha_j)] - \sum_{i=1}^n [\ln \Gamma(|\alpha|+|\mathbf{x}_i|) - \ln \Gamma(|\alpha|)]
$$
By taking first derivative of $L(\alpha)$ respect to each element in vector $\alpha$, we get the socre function to be as follow,
$$
\begin{align}
\nabla L(\alpha) 
&= \sum_{i = 1}^n (\Psi(\alpha_j+x_{ij})-\Psi(\alpha_j)) - \sum_{i=1}^n(\Psi(|\alpha|+|x_i|)-\Psi(|\alpha|))\\
&= \sum_{i = 1}^n (\Psi(\alpha_j+x_{ij})-\Psi(\alpha_j)) - \sum_{i=1}^n\Psi(|\alpha|+|x_i|)+n\Psi(|\alpha|)
\end{align}
$$
where $\Psi(x)= \frac{d}{dx}log\Gamma(x)$ is the digamma function.
* **observed information matrix**

$$
-d^2L(\alpha)=-\frac{d\nabla L(\alpha)}{d\alpha}
=\sum_{i = 1}^n[\Psi'(\alpha_j)-\Psi'(\alpha_j+x_{ij})]-\sum_{i = 1}^n[\Psi'(|\alpha|)-\Psi'(|\alpha|+|x_i|)]
$$
(1) diagonal matrix part, $D$

When taking the second derivative respect to $\alpha$, the terms with only $\alpha_j$ will pretain if both of the derivatives taken respect to $\alpha_j$. That is $\Psi'(\alpha_j)$ and $\Psi'(\alpha_j+x_{ij})$ terms will only appear on the diaganol of observed information matrix. Therefore, let's define a diagonal matrix $D$, which has the $j^{th}$diagonal entry shown as
$\sum_{i = 1}^n[\Psi'(\alpha_j)-\Psi'(\alpha_j+x_{ij})]$.
From recurrence relation of polygamma function $\Psi^{(m)}(z+1)=\Psi^{(m)}(z)+\frac{(-1)^mm!}{z^{m+1}}$, the trigamma function$\Psi'(z+1)=\Psi^{(1)}(z+1)=\Psi^{(1)}(z)+\frac{(-1)^mm!}{z^{m+1}}$.

Then,
$$
\begin{align}
&\Psi^{(1)}(\alpha_j+1)=\Psi^{(1)}(\alpha_j)-\frac{1}{\alpha_j^2}\\
&\Psi^{(1)}(\alpha_j+2)=\Psi^{(1)}(\alpha_j+1)-\frac{1}{\alpha_j^2+1}\\
&.\\
&.\\
&.\\
&\Psi^{(1)}(\alpha_j+x_{ij})=\Psi^{(1)}(\alpha_j+x_{ij}-1)-\frac{1}{(\alpha_j+x_{ij}-1)^2}
\end{align}
$$
By suming all the above equations, we get
$\Psi'(\alpha_j)-\Psi'(\alpha_j+x_{ij})=\sum_{p=0}^{x_{ij}-1} \frac{1}{(\alpha_j+p)^2}$
Therefore, the $j_{th}$ diagonal position in matrix $D$, 
$$\sum_{i = 1}^n[\Psi'(\alpha_j)-\Psi'(\alpha_j+x_{ij})]=\sum_{i = 1}^n\sum_{p=0}^{x_{ij}-1} \frac{1}{(\alpha_j+p)^2}$$
(2) other part, $m$

Similarly, the terms left in the observated information matrix is 
$$
m= \sum_{i = 1}^n[\Psi'(|\alpha|)-\Psi'(|\alpha|+|x_i|)]
= \sum_{i = 1}^n\sum_{p=0}^{|x_{i}|-1} \frac{1}{(|\alpha|+p)^2}
,$$ which is a constant over the whole matrix.

Therefore, the observed info matrix can be written as 
$\mathbf{D}-m\mathbf{1}\mathbf{1}'$, where $\mathbf{D}$ and $m$ are defined previously.

* **Fisher information matrix $\mathbf{E}[-d^2L(\alpha)]$ **

$$
\begin{align}
\mathbf{E}[-d^2L(\alpha)]
&=\mathbf{E}(\mathbf{D}-m\mathbf{1}\mathbf{1}')\\
&=\mathbf{E}(\mathbf{D})-m\mathbf{1}\mathbf{1}'\\
\end{align}
$$
For calculating the expected value, we need to integrate over $\alpha$, which does not have analytical solution. Therefore, Fisher scoring method is insufficient for computing MLE in this example.



### Question 6

What structure does the observed information matrix possess that can facilitate the evaluation of the Newton direction? Is the observed information matrix always positive definite? What remedy can we take if it fails to be positive definite? (Hint: HW1 Q6.)

* **Solution**

1.special structure

From part 5, we can see the observed information matrix $[-d^2L(\alpha)]=\mathbf{D}-m\mathbf{1}\mathbf{1}'$, where $D$ is a diagonal matrix with $j^{th}$ diagonal entry, $\sum_{i = 1}^n\sum_{p=0}^{x_{ij}-1} \frac{1}{(\alpha_j+p)^2}$ and $m=\sum_{i = 1}^n\sum_{p=0}^{|x_{i}|-1} \frac{1}{(|\alpha|+p)^2}$ is a constant. Therefore the observed information matrix is composed by a diagonal matrix and a rank one matrix. 

2.not always positive difinite 
$$
\begin{align}
det[-d^2L(\alpha)] 
&= det[\mathbf{D}-m\mathbf{1}\mathbf{1}'] \\
&= det[\mathbf{D}(\mathbf{I}-\mathbf{D}^{-1}m\mathbf{1}\mathbf{1}')] \\
&= det(\mathbf{D})det(\mathbf{I}-m\mathbf{D}^{-1}\mathbf{1}\mathbf{1}')\\
&= (\prod_{j}d_j)(1-\sum_j\frac{m}{d_j})
\end{align}
$$
In order to make the matrix positive definite, the determant of the matrix should be positive. From the above equation, that is $1-\sum_j\frac{m}{d_j}>0$ should be satisfied. However, it is not always the case. Therefore, the matrix is not necessarily positive definite.

3.remedy for pd

In order to make the matrix positive definite, $1-\sum_j\frac{m}{d_j}>0$ should be satisfied. That is, $m<\frac{1}{\sum_j(dj^{-1})}$

Therefore, we can take the remedy according to the following rules,
$$
m_{new} = 
\begin{cases}
m & \text{if } m<\frac{1}{\sum_j(dj^{-1})}\\
0.9 \frac{1}{\sum_j(dj^{-1})}& \text{o.w.}  
\end{cases}
$$

4.facillitate the evaluation of the Newton direction.


With the Sherman-Morrison formula, $$
	(\mathbf{A} + \mathbf{u} \mathbf{u}^T)^{-1} = \mathbf{A}^{-1} - \frac{1}{1 + \mathbf{u}^T \mathbf{A}^{-1} \mathbf{u}} \mathbf{A}^{-1} \mathbf{u} \mathbf{u}^T \mathbf{A}^{-1},
$$

$$
\begin{align}
[-d^2L(\alpha)]^{-1}
&= [\mathbf{D}-m\mathbf{1}\mathbf{1}']^{-1}\\
&= \mathbf{D}^{-1}+\frac{m}{1+m\mathbf{1}'\mathbf{D}^{-1}\mathbf{1}}\mathbf{D}^{-1}\mathbf{1}\mathbf{1}'\mathbf{D}^{-1}\\
&= \mathbf{D}^{-1}+\frac{1}{m^{-1}+\mathbf{1}'\mathbf{D}^{-1}\mathbf{1}}\mathbf{D}^{-1}\mathbf{1}\mathbf{1}'\mathbf{D}^{-1}\\
\end{align}
$$

In this way, the inverse of observed info matrix can be decomposed to calculate the inverse of a diagonal matrix $\mathbf{D}$. In this way, the evaluation of the Newton direction can be facillitated.

### Question 7

Discuss how to choose a good starting point. Implement this as the default starting value in your function below. (Hint: Method of moment estimator may furnish a good starting point.)

* **Solution**

From the Dirichlet distruibution, we have the first and second theoritical moments shown as below,
$$
\mathbf{E}(p_k)=\frac{\alpha_k}{|\alpha|}
$$
$$
\mathbf{E}(p_k^2)=\frac{\alpha_k(\alpha_k+1)}{|\alpha|(1+|\alpha|)}
$$
then
$$
\sum_k\frac{\mathbf{E}(p_j^2)}{\mathbf{E}(p_j)} 
= \sum_k\frac{\frac{\alpha_k(\alpha_k+1)}{|\alpha|(1+|\alpha|)}}{\frac{\alpha_k}{|\alpha|}}
= \sum_k\frac{\alpha_k+1}{1+|\alpha|}
= \frac{|\alpha|+d}{|\alpha|+1}
$$
From the n observations, we have the first and second sample moments shown as below,
$$
\mathbf{E}(p_k)=\frac{1}{n}\sum_{i=1}^n\frac{x_{ik}}{|x_i|}
$$
$$
\mathbf{E}(p_k^2)=\frac{1}{n}\sum_{i=1}^n(\frac{x_{ik}}{|x_i|})^2
$$
then let constant c defined as follow,
$$
c=\sum_k\frac{\mathbf{E}(p_j^2)}{\mathbf{E}(p_j)} 
=\sum_k\frac{\frac{1}{n}\sum_{i=1}^n(\frac{x_{ik}}{|x_i|})^2}{\frac{1}{n}\sum_{i=1}^n\frac{x_{ik}}{|x_i|}}
=\sum_k\frac{\sum_{i=1}^n(\frac{x_{ik}}{|x_i|})^2}{\sum_{i=1}^n\frac{x_{ik}}{|x_i|}}
$$
Therefore,
$$
\frac{|\alpha|+d}{|\alpha|+1}=c\\
(c+1)|\alpha|=d-c\\
|\alpha|=\frac{d-c}{c-1}
$$
In order to get each elements in $\alpha$, 
$$
\alpha_k = |\alpha|\mathbf{E}(p_k)=\frac{d-c}{c-1}\frac{\sum_i x_{ik}}{\sum_i|\mathbf{x_i}|}
$$
where $c=\sum_k\frac{\sum_{i=1}^n(\frac{x_{ik}}{|x_i|})^2}{\sum_{i=1}^n\frac{x_{ik}}{|x_i|}}$

In this way, we can use the given data $x_{ik}$ where $i$ from 1 to number of all data points and $k$ is from 1 to $d=64$ to calculate the initial $\alpha$.

### Question 8

Write a function for finding MLE of Dirichlet-multinomial distribution given iid observations $\mathbf{x}_1,\ldots,\mathbf{x}_n$, using the Newton's method. 

* **function to calculate score**

$$
\nabla L(\alpha) 
= \sum_{i = 1}^n (\Psi(\alpha_j+x_{ij})-\Psi(\alpha_j)) - \sum_{i=1}^n(\Psi(|\alpha|+|x_i|)-\Psi(|\alpha|))\\
$$

In [137]:
#Pkg.add("SpecialFunctions.jl")
using SpecialFunctions

# define the function to calculate score function of log-likelihood
# take column of X as one data point
function dirmult_score(X::Matrix, α::Vector)
    # initialize output 
    score = zeros(length(α))
    
    # sum of alpha vector
    sumα = sum(α)
    
    # column sum of X
    colsumX = sum(X, 1)
    
    # store the size of n and d
    n = size(X, 2)
    d = size(X, 1)
    
    # evalutate score function at input α
    for j in 1:d
        for i in 1:n
            score[j] += digamma(α[j] + X[j, i]) - digamma(α[j]) - 
                digamma(sumα + colsumX[i]) + digamma(sumα)
            end 
    end
    
    # return vector score
    return score 
end

dirmult_score (generic function with 2 methods)

In [138]:
# test for score function
dirmult_score(train_x', α)


64-element Array{Float64,1}:
 -6809.0  
 -5994.02 
   399.53 
  4465.77 
  4255.45 
  -239.022
 -4871.03 
 -6583.75 
 -6804.21 
 -3509.27 
  3477.72 
  4619.83 
  3901.48 
     ⋮    
  3294.76 
  2375.96 
 -2036.58 
 -6477.55 
 -6808.0  
 -6101.94 
   525.922
  4463.0  
  3988.35 
   655.835
 -3961.5  
 -6442.54 

* **function to calculate observed info matrix**

The observed info matrix can be written as $\mathbf{D}-m\mathbf{1}\mathbf{1}'$, where $\mathbf{D}$ and $m$ are defined as follow:

$j_{th}$ diagonal position in matrix $D$,
$$d_j=\sum_{i = 1}^n[\Psi'(\alpha_j)-\Psi'(\alpha_j+x_{ij})]$$
and 
$$
m= \sum_{i = 1}^n[\Psi'(|\alpha|)-\Psi'(|\alpha|+|x_i|)]
$$

In [139]:
# define the function to calculate the observed information matrix 
# return diagonal vector d and constant m for recovery
# take column of X as one data point
function dirmult_obs(X::Matrix, α::Vector)
    # obs matrix = Diagonal(d) - m11'
    # initialization 
    d = zeros(length(α))
    m = 0.0
    
    # store the size of n and number of parameters
    n = size(X, 2)
    par = size(X, 1)
    
    # sum of alpha vector
    sumα = sum(α)
    
    # column sum of X
    colsumX = sum(X, 1)
    
    # evaluation d 
    for j in 1:par
        for i in 1:n
            d[j] += trigamma(α[j]) - trigamma(α[j] + X[j, i])
        end
    end
    
    # evaluation m
    for i in 1:n
        m += trigamma(sumα) - trigamma(sumα + colsumX[i])
    end
    
    return m, d
    
end

dirmult_obs (generic function with 3 methods)

In [165]:
# test for obs matrix fcn
dirmult_obs(train_x', α)

(50.0163869748493, [0.0, 688.915, 4313.97, 5730.92, 5665.9, 3860.62, 1242.08, 151.565, 3.71361, 2231.94  …  2853.36, 255.11, 1.0, 574.829, 4306.32, 5688.55, 5469.75, 4162.56, 1787.01, 264.045])

* **initial $\mathbf{α}$**

The $k^{th}$ element in initial $\mathbf{α}$ is 
$$
\alpha_k = \frac{d-c}{c-1}\frac{\sum_i x_{ik}}{\sum_i|\mathbf{x_i}|}
$$
where $c=\sum_k\frac{\sum_{i=1}^n(\frac{x_{ik}}{|x_i|})^2}{\sum_{i=1}^n\frac{x_{ik}}{|x_i|}}$
and 
$d$ is the length of $\mathbf{α}$ 


In [141]:
# define the function to calculate the initial value for α
# take column of X as one data point
function dirmult_α0(X::Matrix)
    # initialization
    α0 = zeros(length(α))
    c = 0.0
    
    # store the size of n and number of parameters 
    n = size(X, 2)
    d = size(X, 1)
    
    # sum of alpha vector
    sumα = sum(α)
    
    # column sum of X
    colsumX = sum(X, 1)
    
    # total of X
    total = sum(colsumX)
    
    # evaluate c 
    for k in 1:d
        denumerator = sum(X[k, :] ./ colsumX)
        if  denumerator > 0
            c += sum(X[k, :].^2 ./ colsumX.^2) / denumerator 
        end
    end
    
        
    # evaluate α0 and make sure αsum is nonegative
    α0 = max((d - c) / (c - 1), 1e-4) / total * sum(X, 2)
    
    return α0
    
end


dirmult_α0 (generic function with 2 methods)

In [142]:
# test for initial alpha
dirmult_α0(train_x')

64×1 Array{Float64,2}:
 0.0        
 0.0683308  
 1.24306    
 2.67712    
 2.59675    
 1.2484     
 0.314606   
 0.0322673  
 0.000474519
 0.444565   
 2.39852    
 2.6566     
 2.40931    
 ⋮          
 2.21428    
 2.10509    
 0.848974   
 0.0336316  
 5.93149e-5 
 0.0641787  
 1.32788    
 2.7082     
 2.59894    
 1.51941    
 0.477485   
 0.0458504  

* **implement of Newton's method**

In [446]:
"""
    dirmult_newton(X)

Find the MLE of Dirichlet-multinomial distribution using Newton's method.

# Argument
* `X`: an `n`-by-`d` matrix of counts; each column is one data point.

# Optional argument  
* `alpha0`: a `d` vector of starting point (optional). 
* `maxiters`: the maximum allowable Newton iterations (default 100). 
* `tolfun`: the tolerance for  relative change in objective values (default 1e-6). 

# Output
* `maximum`: the log-likelihood at MLE.   
* `estimate`: the MLE. 
* `gradient`: the gradient at MLE. 
* `hessian`: the Hessian at MLE. 
* `se`: a `d` vector of standard errors. 
* `iterations`: the number of iterations performed.
"""

function dirmult_newton(X::Matrix; α0::Vector = nothing, 
            maxiters::Int = 100, tolfun::Float64 = 1e-6)
    # store original size of α
    α_d = size(X, 1)
    
    # remove rows with all 0 entries
    row_ind = find(sum(X, 2))
    col_ind = find(sum(X, 1))
    
    # get the new X removing all the 0 sum lines
    X_nz = X[row_ind, :]
    
    # store the number of parameters 
    d = size(X_nz, 1)
    
    # initialization
    α_old = α0[row_ind]
    logl_old = sum(dirmult_logpdf(X_nz, α_old))
    
    # pre-allocation 
    α_new = zeros(d)
    gradient = zeros(d)
    
    logl_new = 0.0
    newtondir = zeros(d)
    
    # obs matrix = diagonal(D_diag) - m11'
    D_diag = zeros(d)
    m = 0.0
    # check for pd remedy 
    m_bound = 0.0 
    
    # iteration count
    iteration = 0
    
    # Newton loop
    for iter in 1:maxiters
        # evaluate gradient (score)
        gradient = dirmult_score(X_nz, α_old)
        
        # compute inverse obs matrix
        m, D_diag = dirmult_obs(X_nz, α_old)
        
        # remedy for making sure obs matrix is pd
        sum_dinv = sum(1 ./ D_diag)
        
        if m >= 1 / sum_dinv
            m = 0.95 * 1 / sum_dinv
        end
        
        # compute Newton's direction based on Sherman-Morrison formula
        newtondir .= (1 ./ D_diag) .* gradient + 1 / (1 / m - sum_dinv) *
            ((1 ./ D_diag).^2) .* gradient
        
        # line search loop
        for lsiter in 1:10
            # step halving
            step = 0.5^(lsiter - 1)
            
            # get new α
            α_new .= α_old + step .* newtondir
            logl_new = sum(dirmult_logpdf(X_nz, α_new))
            
            # check for getting higher loglikelihood fcn
            if logl_new > logl_old
                break
            end
        end
        
        # check convergence criterion
        if abs(logl_new - logl_old) < tolfun * (abs(logl_old) + 1)
            # update before break the loop
            α_old = copy(α_new)
            logl_old = logl_new
            iteration += 1
            break;
        end
        
        # update 
        α_old = copy(α_new)
        logl_old = logl_new
        iteration += 1
        
    end
    
    # add zeros back to α vector
    α = zeros(α_d)
    α[row_ind] = α_old[1:d]

    
    
    # compute logl, gradient, Hessian from final iterate
    logl = sum(dirmult_logpdf(X_nz, α))
    gradient = dirmult_score(X_nz, α)
    m, D_diag = dirmult_obs(X_nz, α)
    hessian = (Diagonal(vec(D_diag)) - m * ones(α_d, α_d)) * (-1)

    # output
    return α, logl, gradient, hessian, m, D_diag, iteration, α_d
    
end

dirmult_newton

In [409]:
α0 = vec(dirmult_α0(train_x'));

In [448]:
dirmult_newton(train_x', α0 = α0)[1]

64-element Array{Float64,1}:
 0.0        
 0.0805772  
 0.888965   
 2.08629    
 2.00262    
 0.759017   
 0.145656   
 0.0150775  
 0.000387975
 0.299797   
 1.73341    
 2.12608    
 1.8558     
 ⋮          
 1.64636    
 1.39109    
 0.456776   
 0.0271295  
 0.000129274
 0.0651678  
 0.913522   
 2.0955     
 1.92583    
 0.938191   
 0.230338   
 0.0276724  

In [439]:
result = dirmult_newton(train_x', α0 = α0)
obs = Diagonal(vec(D_diag)) - m * ones(d, d)
det(obs)
result[1]


([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0276724, 0.0, 0.0], -525538.0707315523, [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN  …  NaN, NaN, NaN, NaN, NaN, NaN, NaN, -154416.0, 0.0, 0.0], [NaN 4.99845e6 … 4.99845e6 4.99845e6; 4.99845e6 NaN … 4.99845e6 4.99845e6; … ; 4.99845e6 4.99845e6 … 4.99845e6 4.99845e6; 4.99845e6 4.99845e6 … 4.99845e6 4.99845e6], 4.998449589767135e6, [NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN  …  NaN, NaN, NaN, NaN, NaN, NaN, NaN, 2.70494e5, 0.0, 0.0], 43, 64)

### Question 9

Read in `optdigits.tra`, the training set of 3823 handwritten digits. Find the MLE for the subset of digit 0, digit 1, ..., and digit 9 separately using your function. 

In [378]:
# read in train data
path1_tra = "http://hua-zhou.github.io/teaching/biostatm280"
path2_tra = "-2018spring/hw/hw4/optdigits.tra"

train = readdlm(download(path1_tra * path2_tra), ',')

# separte last column which store the digit 
train_x = round.(Int64, train[:, 1:64])
train_digit = round.(Int64, train[:, 65]);



In [392]:
a=view(train, 1:10, 60:65)
display(a)
display(a[:, 6])
a[a[:, 6] .== 5.0, :]

10×6 SubArray{Float64,2,Array{Float64,2},Tuple{UnitRange{Int64},UnitRange{Int64}},false}:
 14.0   7.0   1.0   0.0  0.0  0.0
 16.0  15.0   3.0   0.0  0.0  0.0
 14.0   0.0   0.0   0.0  0.0  7.0
  1.0  15.0   2.0   0.0  0.0  4.0
 12.0  14.0   7.0   0.0  0.0  6.0
 16.0  16.0  16.0  16.0  6.0  2.0
 13.0   5.0   0.0   0.0  0.0  5.0
 13.0   8.0   0.0   0.0  0.0  5.0
 12.0   5.0   0.0   0.0  0.0  0.0
 15.0  11.0   6.0   0.0  0.0  8.0

10-element Array{Float64,1}:
 0.0
 0.0
 7.0
 4.0
 6.0
 2.0
 5.0
 5.0
 0.0
 8.0

2×6 Array{Float64,2}:
 13.0  5.0  0.0  0.0  0.0  5.0
 13.0  8.0  0.0  0.0  0.0  5.0

In [421]:
X_0 = X[X[:, 65] .== 0, 1:64]
X_1 = X[X[:, 65] .== 1, 1:64]
#dirmult_newton(X_0', α0 = α0)[1]
#dirmult_newton(X_1', α0 = α0)[1]
    # remove rows with all 0 entries
    row_ind = find(sum(X_0, 2))
    #col_ind = find(sum(X_0, 1))
    #display(row_ind)
    # get the new X removing all the 0 sum lines
    X_nz = X[row_ind, :]
    

376×65 Array{Int64,2}:
 0  1   6  15  12   1   0  0  0   7  16  …  0  0  0   6  14   7   1   0  0  0
 0  0  10  16   6   0   0  0  0   7  16     0  0  0  10  16  15   3   0  0  0
 0  0   8  15  16  13   0  0  0   1  11     0  0  0   9  14   0   0   0  0  7
 0  0   0   3  11  16   0  0  0   0   5     0  0  0   0   1  15   2   0  0  4
 0  0   5  14   4   0   0  0  0   0  13     0  0  0   4  12  14   7   0  0  6
 0  0  11  16  10   1   0  0  0   4  16  …  3  0  0  10  16  16  16  16  6  2
 0  0   1  11  13  11   7  0  0   0   9     0  0  0   1  13   5   0   0  0  5
 0  0   8  10   8   7   2  0  0   1  15     0  0  0   4  13   8   0   0  0  5
 0  0  15   2  14  13   2  0  0   0  16     0  0  0  10  12   5   0   0  0  0
 0  0   3  13  13   2   0  0  0   6  16     0  0  0   3  15  11   6   0  0  8
 0  0   6  14  14  16  16  8  0   0   7  …  0  0  0  10  12   0   0   0  0  7
 0  0   0   3  16  11   1  0  0   0   0     0  0  0   0   2  14  14   1  0  1
 0  0   0   4  13  16  16  3  0   0   8  

In [485]:
# convert the training data set to Int64
X = round.(Int64, train);

# initialize matrix to store 
α_all = zeros(64, 10) 

for digit in 1
    # get the train_x subset for different digits
    X_digit = X[X[:, 65] .== digit, 1:64]
    α0 = vec(dirmult_α0(X_digit'))
    @show α0 
    # get 
    #α_all[:, (digit + 1)] .= 
    @show dirmult_newton(X_digit', α0 = α0)[1]
    
    
    
end

α0 = [0.0, 0.00455717, 0.69269, 2.66443, 3.27205, 1.7059, 0.153425, 0.0, 0.0, 0.0645599, 1.41196, 3.72473, 4.38172, 2.73127, 0.268873, 0.0, 0.00987387, 0.4185, 2.38492, 4.33615, 4.40755, 2.41378, 0.16178, 0.0, 0.00303812, 0.723071, 2.98647, 4.33691, 4.33615, 2.21631, 0.135196, 0.0, 0.0, 0.481541, 2.20415, 3.56751, 4.28222, 2.14719, 0.119246, 0.0, 0.0, 0.11317, 1.3907, 3.11483, 4.20019, 2.28238, 0.164818, 0.0, 0.0, 0.040255, 1.32158, 3.2318, 4.27463, 2.81709, 0.48382, 0.0562051, 0.0, 0.0113929, 0.688133, 2.55202, 3.71334, 2.65531, 0.688893, 0.147349]
(dirmult_newton(X_digit', α0=α0))[1] = [0.0, 0.0183493, 1.40104, 6.32803, 9.02642, 3.82976, 0.331836, 0.0, 0.0, 0.134288, 3.03424, 10.0597, 12.0435, 6.66139, 0.449188, 0.0, 0.0148685, 0.626685, 5.68392, 11.9302, 12.0181, 5.54624, 0.260292, 0.0, 0.0146434, 1.40655, 7.7252, 11.9444, 11.9094, 4.99621, 0.221519, 0.0, 0.0, 0.916353, 4.93265, 9.48779, 11.8298, 4.82205, 0.189065, 0.0, 0.0, 0.249257, 2.44194, 7.56206, 11.6648, 5.22852, 0.244245, 0.

In [493]:
X1 = round.(Int64, train);
X = (X1[X1[:, 65] .== 1, 1:64])'

    # store original size of α
    α_d = size(X, 1)
    
    # remove rows with all 0 entries
    row_ind = find(sum(X, 2))
    col_ind = find(sum(X, 1))
    
    # get the new X removing all the 0 sum lines
    X_nz = X[row_ind, :]
    
    # store the number of parameters 
    d = size(X_nz, 1)
    
    # initialization
    α0 = dirmult_α0(X)
    α_old = α0[row_ind]
    logl_old = sum(dirmult_logpdf(X_nz, α_old))
    
    # pre-allocation 
    α_new = zeros(d)
    gradient = zeros(d)
    
    logl_new = 0.0
    newtondir = zeros(d)
    
    # obs matrix = diagonal(D_diag) - m11'
    D_diag = zeros(d)
    m = 0.0
    # check for pd remedy 
    m_bound = 0.0 
    
    # iteration count
    iteration = 0



for iter in 1
        # evaluate gradient (score)
        gradient = dirmult_score(X_nz, α_old)
    
        
        # compute inverse obs matrix
        m, D_diag = dirmult_obs(X_nz, α_old)
        
        # remedy for making sure obs matrix is pd
        sum_dinv = sum(1 ./ D_diag)
        @show sum_dinv
    
        if m >= 1 / sum_dinv
            m = 0.95 * 1 / sum_dinv
        end
        @show m
        
        # check pd
        obs = Diagonal(vec(D_diag)) - m * ones(d, d)
        @show det(obs)
        
    
        # compute Newton's direction based on Sherman-Morrison formula
        newtondir .= (1 ./ D_diag) .* gradient + 1 / (1 / m - sum_dinv) *
            ((1 ./ D_diag).^2) .* gradient
        @show newtondir
        
        # line search loop
        for lsiter in 1:2
            # step halving
            step = 0.5^(lsiter - 1)
            
            # get new α
            α_new .= α_old + step .* newtondir
            logl_new = sum(dirmult_logpdf(X_nz, α_new))
            
            # check for getting higher loglikelihood fcn
            if logl_new > logl_old
                break
            end
        end
    
        # check convergence criterion
        if abs(logl_new - logl_old) < 1e-6 * (abs(logl_old) + 1)
            # update before break the loop
            α_old = copy(α_new)
            logl_old = logl_new
            iteration += 1
            break;
        end
        
        # update 
        α_old = copy(α_new)
        logl_old = logl_new
        iteration += 1
        
    end

α_old 
        

sum_dinv = 0.2979935880757474
m = 3.1145035392971185
det(obs) = 6.614177955021555e138
newtondir = [0.00217632, -0.145322, -0.32907, 0.343614, -0.253604, -0.00244879, -0.00214138, -0.294864, 0.0583917, 0.549382, -0.212786, -0.098471, -0.00398023, -0.244769, -0.227718, 0.570924, 0.605744, -0.381936, -0.0617552, 0.00171308, -0.195795, 0.0231154, 0.55724, 0.590751, -0.396347, -0.0473989, -0.123812, -0.4181, 0.0145702, 0.555543, -0.388321, -0.0467336, 0.00131763, -0.731571, -0.392634, 0.514463, -0.359141, -0.0820093, -0.000703281, -0.615894, -0.233743, 0.592259, -0.255434, -0.293289, -0.0394985, 0.00466516, -0.137428, -0.297273, 0.486891, -0.137212, -0.360346, -0.333323]


52-element Array{Float64,1}:
  0.0067335 
  0.547368  
  2.33536   
  3.61566   
  1.4523    
  0.150976  
  0.0624186 
  1.1171    
  3.78312   
  4.9311    
  2.51848   
  0.170402  
  0.00589365
  ⋮         
  2.99805   
  4.86689   
  2.56166   
  0.190531  
  0.0167067 
  0.0160581 
  0.550705  
  2.25474   
  4.20023   
  2.5181    
  0.328547  
 -0.185974  

In [494]:
x = [-1, 1,4,3,4,4];
f(x) = x == 4
find(f(4), x)
length(x[x .< 0])

LoadError: MethodError: no method matching find(::Bool, ::Array{Int64,1})
Closest candidates are:
  find(::Compat.OccursIn, ::Any) at C:\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\Users\Dell\AppData\Local\JuliaPro-0.6.2.2\pkgs-0.6.2.2\v0.6\Compat\src\Compat.jl:1538
  find(::Function, ::Any) at array.jl:1518
  find(::Number) at array.jl:1569
  ...