# M280 Homework 2
* Author: Shuang Gao
* Date: 2018/05/02

## Question 1

1.1 Implement the algorithm with arguments:  $X$  (data, each row is a vectorized image), rank  $r$ , convergence tolerance, and optional starting point.

In [5]:
function nnmf(
 X::Matrix, 
 r::Int;
 maxiter::Int = 1000, # change iteration from 1000 to 2
 tol::Float64 = 1e-4
 )  
    # readin matrix V0
    path_V0 = "http://Hua-Zhou.github.io/teaching/biostatm280-2018spring/hw/hw2/V0.txt"
    V0 = readdlm(download(path_V0), ' ')

    # readin matrix W0
    path_W0 = "http://Hua-Zhou.github.io/teaching/biostatm280-2018spring/hw/hw2/W0.txt"
    W0 = readdlm(download(path_W0), ' ')

    V = V0[:, 1:r]
    W = W0[1:r, :]
    
    
    # input V W 
    #V = rand(size(X, 1), r)
    W = rand(r, size(X, 2))
    
    # initilize two matrices 
    V_new = zeros(size(V))
    W_new = zeros(size(W))
    
    for t in 1:maxiter # stop after 1000 iterations
        # update v by element
        for k in 1:r, i in 1:size(X, 1)
            # initialize float number for denomenator
            denomenator = 0.0
            # update denomenator 
            for j in 1:size(X, 2)
                denomenator += dot(V[i, :], W[:, j]) * W[k, j]
            end
            # update element V_ik
            V_new[i, k] = V[i, k] * dot(X[i, :], W[k, :]) / denomenator 
        end


        
        # update W by element
        for j in 1:size(X, 2), k in 1:r
            # initialize float number for denomenator
            denomenator = 0.0
            # update denomenator 
            for i in 1:size(X, 1)
                denomenator += dot(V_new[i, :], W[:, j]) * V_new[i, k]
            end
            # update element W_kj
            W_new[k, j] = W[k, j] * dot(X[:, j], V_new[:, k]) / denomenator 
        end
        
        # update V W 
        V = copy(V_new)
        W = copy(W_new) 
        
        # calculate Frobenius norm after each iteration
        norm = 0.0
        for j = 1:size(X, 2), i = 1:size(X, 1)
            norm += (X[i, j] - dot(V[i, :], W[:, j]))^2 
        end
    
        # exit loop if norm less than tolerance
        if norm <= tol
            exit 
        end
    end      
    
    # Output
    return V, W
end
    
    

nnmf (generic function with 1 method)

1.2 Database 1 from the MIT Center for Biological and Computational Learning (CBCL) reduces to a matrix  $X$  containing  $m=2,429$  gray-scale face images with  $n=19×19=361$  pixels per face. Each image (row) is scaled to have mean and standard deviation 0.25.
Read in the nnmf-2429-by-361-face.txt file, e.g., using readdlm() function, and display a couple sample images, e.g., using ImageView.jl package.

In [3]:
# add package for visulizating image
#Pkg.add("ImageView")
#Pkg.add("Images")
#Pkg.add("TestImages")
#Pkg.build("Cairo")
Pkg.pin("Cairo", v"0.4.0")
#Pkg.update()
using ImageView, Images

# readin matrix file
path_X = "http://Hua-Zhou.github.io/teaching/biostatm280-2018spring/hw/hw2/nnmf-2429-by-361-face.txt"

X = readdlm(download(path_X), ' ')

# show first three face images
#for i in 1:3
    # extract one row pixels to form one face image
    img = reshape(X[1, :], 19, 19)
    imshow(img)
#end
    


INFO: Package Cairo is already pinned to the selected commit


Dict{String,Any} with 4 entries:
  "gui"         => Dict{String,Any}(Pair{String,Any}("window", Gtk.GtkWindowLea…
  "roi"         => Dict{String,Any}(Pair{String,Any}("redraw", 145: "map(clim-m…
  "annotations" => 111: "input-38" = Dict{UInt64,Any}() Dict{UInt64,Any} 
  "clim"        => 110: "CLim" = ImageView.CLim{Float64}(0.0, 0.93656) ImageVie…

ERROR: Cairo.CairoContext must implement reset_transform


1.3  

In [14]:
# readin matrix X
path_X = "http://Hua-Zhou.github.io/teaching/biostatm280-2018spring/hw/hw2/nnmf-2429-by-361-face.txt"
X = readdlm(download(path_X), ' ')

# readin matrix V0
path_V0 = "http://Hua-Zhou.github.io/teaching/biostatm280-2018spring/hw/hw2/V0.txt"
V0 = readdlm(download(path_V0), ' ')

# readin matrix W0
path_W0 = "http://Hua-Zhou.github.io/teaching/biostatm280-2018spring/hw/hw2/W0.txt"
W0 = readdlm(download(path_W0), ' ');


In [ ]:
# when r = 10
@time nnmf(X, 10, maxiter = 1000, tol = 1e-4)
@time nnmf(X, 10, maxiter = 1000, tol = 1e-4)

In [ ]:
# when r = 20
@time nnmf(X, 20, maxiter = 1000, tol = 1e-4)
@time nnmf(X, 20, maxiter = 1000, tol = 1e-4)

In [ ]:
# when r = 30
@time nnmf(X, 30, maxiter = 1000, tol = 1e-4)
@time nnmf(X, 30, maxiter = 1000, tol = 1e-4)

In [ ]:
# when r = 40
@time nnmf(X, 40, maxiter = 1000, tol = 1e-4)
@time nnmf(X, 40, maxiter = 1000, tol = 1e-4)

In [ ]:
##### when r = 50
@time nnmf(X, 50, maxiter = 1000, tol = 1e-4)
@time nnmf(X, 50, maxiter = 1000, tol = 1e-4)

In [ ]:
function nnmf(
 X::Matrix, 
 r::Int;
 maxiter::Int = 1000, # change iteration from 1000 to 2
 tol::Float64 = 1e-4
 )  

In [32]:
2.0^(-2)

0.25

In [11]:
# readin matrix file
path_X = "http://Hua-Zhou.github.io/teaching/biostatm280-2018spring/hw/hw2/nnmf-2429-by-361-face.txt"

X = readdlm(download(path_X), ' ')

2429×361 Array{Float64,2}:
 0.14815    0.018294   0.027569   0.0        …  0.0       0.0       0.0      
 0.20667    0.095859   0.0020948  0.10438       0.0       0.0       0.0      
 0.020835   0.0        0.13617    0.0030917     0.0       0.0       0.0      
 0.0        0.25467    0.0        0.076619      0.14222   0.020391  0.0      
 0.0082034  0.0        0.16066    0.0           0.089516  0.059024  0.0      
 0.0        0.0        0.0        0.32852    …  0.21551   0.11192   0.027156 
 0.0        0.0        0.0        0.027593      0.28612   0.26544   0.14135  
 0.16249    0.15444    0.0095702  0.0           0.33151   0.33956   0.35566  
 0.090691   0.11932    0.1408     0.04774       0.34839   0.32692   0.29828  
 0.0        0.069167   0.098722   0.1135        0.34994   0.36472   0.32778  
 0.1602     0.0060618  0.0        0.0        …  0.42994   0.42994   0.37214  
 0.02756    0.0        0.11518    0.0           0.045083  0.018798  0.0012747
 0.22345    0.0021421  0.0        0.0

In [36]:
A = rand(5,5)
display(A)
A[1, 1] = 10
display(A)

5×5 Array{Float64,2}:
 0.208376   0.992082  0.597698   0.350974    0.0549897
 0.980541   0.231828  0.10002    0.872671    0.0455036
 0.0200053  0.357273  0.057088   0.908363    0.639969 
 0.996505   0.75005   0.171043   0.405864    0.526456 
 0.449994   0.53021   0.0568716  0.00637239  0.17208  

5×5 Array{Float64,2}:
 10.0        0.992082  0.597698   0.350974    0.0549897
  0.980541   0.231828  0.10002    0.872671    0.0455036
  0.0200053  0.357273  0.057088   0.908363    0.639969 
  0.996505   0.75005   0.171043   0.405864    0.526456 
  0.449994   0.53021   0.0568716  0.00637239  0.17208  